### ISSUE TITLE
Check whether a list of codes in -concept_set_codes- contains the empty string ""

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/CreateConceptSetDatasets#13]
When the function starts it would be useful it it threw a warning indicating that one of the parameters contains the empty string "". THis may be on purpose, so the function should not stop: but there should be a severe warning because what happens then is that *all* the records with the corresponding coding system are retrieved!!!

**Comment by DavideMessinaARS** [comment]
It already exists a value for specifying all of the codes, "ALL_CODES", so should "" still be a warning and not an error?

What should the error/warning print? I would suggest maybe to write a summary in general (ex: n codes are "", use "ALL_CODES" instead of "") to remove this warning) and if verbose is true writing in details which codes contains ""

In case it is a warning should "" be treated the same way "ALL_CODES" is? (after the warning)

**Comment by RosaMGini** [comment]
probably 'all codes' does not refer to a specific coding system, or, does it?

**Comment by DavideMessinaARS** [comment]
ALL_CODES refers to a specific type_cod inside the parameters and how it cycles.

But now that I just noticed, it assign 1 to the filter on all of the rows and not only on the ones with that coding system.

```r
for (type_cod in cod_system_indataset) {
   stop = FALSE
   codes_rev <- concept_set_codes[[concept]][[type_cod]]
   for (single_cod in concept_set_codes[[concept]][[type_cod]]) {
       if (single_cod == "ALL_CODES") {
           print("allcodes")
           used_df[,Filter:=1]
           used_df[,paste0("Col_",concept):=codvar[[dom]][[df2]][1]]
           stop = TRUE
           break
       }
   }
   if (stop == TRUE) {
       next
   }

   do stuff if we have normal codes

}
```

However we could change that easily by using a command similar to the one used below:

```r
used_df[(str_detect(get(col), paste(paste0("^", codes_rev), collapse = "|"))) &
                get(vocabulary[[dom]][[df2]]) == type_cod, c("Filter", 
                        paste0("Col_", concept)) := list(1, col)]
```
