### ISSUE TITLE
Filter input file with an overarching condition on the -rename_col- columns

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/CreateConceptSetDatasets#20]
When loading an input file, the -rename_col- parameter could be enacted first, and then a first selection of the dataset could be performed using an expression in the renamed columns. The expression should be associated to each data domain.

A new parameter could be introduced for this pupose, named
 
filter_expression (optional) this is a 2-level lists: this is a logical condition in the columns that are specified in -rename_col-. This conditions is to be used to filter the input datasets before starting to filter the concept sets

example

filter_our_study <- list()
filter_our_study[['Diagnosis']] = "date >= as.date('20120101')"
filter_our_study[['Medicines']] = "date >= as.date('20150101')"

...
filter_expression = filter_our_study
...

**Comment by DavideMessinaARS** [comment]
I noticed a similar idea was already in place. I've changed the name of the parameter from "filter" to "filter_expression" and added the domain level.

Should the function raise a warning/error if the rename_col parameter is not specified while there is a filter?
In theory, it should work even if the original column names are used in the filter.

In addition, I would propose to write in the documentation that filter_expression is a list of (character) vectors (and not a 2-level list) since that's what I see in the example above and how I've implemented it
